server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

sky:
  mysql:
    database: sky_takeout
  redis:
    database: 0
  alioss:
    bucket-name: rocsoar-sky
    endpoint: oss-cn-beijing.aliyuncs.com