sky:
  server:
    port: 8080
    address: 0.0.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeout
    username: root
    password: "00000000"
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  alioss:
    bucket-name: rocsoar-sky
    endpoint: oss-cn-beijing.aliyuncs.com