spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_DEBIAN}:${MYSQL_PORT}/${sky.mysql.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME_REMOTE}
    password: ${MYSQL_PASSWORD_REMOTE}
  data:
    redis:
      host: ${REDIS_HOST_DEBIAN}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD_REMOTE}
      database: ${sky.redis.database}

mybatis:
  # sql-mapper配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #  在xxxMapper.xml可不用再写全类名
  type-aliases-package: com.sky.entity, com.sky.dto, com.sky.vo
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

#springdoc:
#  # 设置生成openapi3/swagger3接口文档需要扫描的包
#  packages-to-scan: com.sky.controller
#  paths-to-match: /**

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${JWT_SECRET_KEY}
    user-secret-key: ${JWT_SECRET_KEY}
    # 设置jwt过期时间(ms) 200小时
    admin-ttl: 720000000
    user-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-token-name: authentication
  wechat:
    appid: ${WX_APPID}
    secret: ${WX_APP_SECRET}
    mchid: xxx
    mch-serial-no: xxx
    private-key-file-path: xxx
    api-v3-key: xxx
    we-chat-pay-cert-file-path: xxx
    notify-url: http://xx.xx.xx.xx/notify/paySuccess
    refund-notify-url: http://xx.xx.xx.xx/notify/refundSuccess