sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeout
    username: root
    password: "00000000"
  alioss:
    bucket-name: rocsoar-sky
    endpoint: oss-cn-beijing.aliyuncs.com